sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tomersf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tomersf/react-test npm run test

after_success:
  - docker build -t tomersf/multi-client ./client
  - docker build -t tomersf/multi-nginx ./nginx
  - docker build -t tomersf/multi-server ./server
  - docker build -t tomersf/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to docker hub
  - docker push tomersf/multi-client
  - docker push tomersf/multi-nginx
  - docker push tomersf/multi-server
  - docker push tomersf/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-995673743848"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
